### ISSUE TITLE
What do you think about the specific type of data acquisition for Operation

### ISSUE THREAD

**Issue by zengcanxiang** [ILIYANGERMANOV/flawless-requests-demo#1]
Hi, what do you think about the specific type of data acquisition for Operation?

After the when type judgment above, the desired type cannot be obtained in {}, unless as is used and matched with state in compose. I think this is a very bad way of writing and will make people feel frustrated.

![image](https://github.com/user-attachments/assets/ec0933c0-74ea-425f-ab51-ab1b4478314e)

Smart cast to 'Operation. Ok<PeopleResponse>' is impossible, because 'opPeople' is a property that has open or custom getter

**Comment by ILIYANGERMANOV** [comment]
Save `opPeople` in a **val** and do `when(opPeople) { ... }`. In the Ok case.`opPeople.data` should work and fix the compiler smart cast issues.

**Comment by zengcanxiang** [comment]
@ILIYANGERMANOV 
Thank you for your answer

This is how I handle it now
```kotlin
val stateData by xxxx
val data = stateData
when(data){
    is XXx ->{
       data.doSomething()
    }
}
```

Although it is not perfect, it seems to be the only way。

It seems that you think so too. If I have a better idea, I will share it with you again.

Thank you very much.
